server:
  port: 8800
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: thw
    password: thw19971017thw
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    tomcat:
      max-wait: 10000
      min-idle: 20
      max-idle: 100
      max-active: 300
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB #配置单个文件最大上传大小
      max-request-size: 30MB #配置多个文件最大上传大小
  activiti:
    database-schema: update #配置数据库策略，表不存在就创建，存在就不创建
    check-process-definitions: false #配置不检查流程定义是否存在于项目中
  redis:
    host: 192.168.174.128
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 10000
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util
  configuration:
    call-setters-on-nulls: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  hystrix:
    enabled: true
#设置hystrix隔离策略中的延迟时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#监控所有服务
management:
  endpoints:
    web:
      exposure:
        include: "*"
